spring:
  devtools:
    add-properties: true
    livereload:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/observability_db?currentSchema=users"
    username: "admin"
    password: "admin123"

server:
  port: 8080

logging:
  level:
    jp:
      kukv: "debug"

management:
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
    metrics:
      endpoint: "http://localhost:4318/v1/metrics"
    logs:
      endpoint: "http://localhost:4318/v1/logs"
otel:
  exporter:
    otlp:
      endpoint: "http://localhost:4318"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
