---
services:
  postgres:
    build:
      context: "./postgres"
    hostname: "${DB_HOST}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./postgres/init:/docker-entrypoint-initdb.d"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: "10s"
      timeout: "5s"
      retries: 5
