spring:
  application:
    name: "order-api"
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  web:
    resources:
      add-mappings: false
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
    remote:
      restart:
        enabled: false
  datasource:
    url: "${DATASOURCE_URL}"
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-init-sql: "SELECT 1"

server:
  shutdown: "graceful"
  compression:
    enabled: true

logging:
  level:
    jp:
      kukv: "info"
    jp.kukv.user_api.infrastructure.datasource: "debug"

mybatis:
  mapper-locations: "classpath*:/jp/kukv/order_api/infrastructure/datasource/**/*.xml"
  type-handlers-package: "jp.kukv.order_api.infrastructure._configuration.mybatis.typehandler"
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    access:
      default: "none"
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      access: "read_only"
      probes:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: true
        url: "${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics"
        step: "10s"
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces"
    logging:
      export:
        otlp:
          endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs"
    resource-attributes:
      service.name: "${spring.application.name}"
      deployment.environment: "${DEPLOYMENT_ENVIRONMENT}"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  packages-to-scan: "jp.kukv.order_api.presentation.endpoint"
  paths-to-match: "/v1/**"

external:
  endpoint:
    user-api:
      domain: "${USER_API_DOMAIN}"
      port: "${USER_API_PORT}"
    product-api:
      domain: "${PRODUCT_API_DOMAIN}"
      port: "${PRODUCT_API_PORT}"
