spring:
  devtools:
    add-properties: true
    livereload:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/observability_db?currentSchema=orders"
    username: "admin"
    password: "admin123"

server:
  port: 8082

logging:
  level:
    jp:
      kukv: "debug"

management:
  endpoints:
    access:
      default: "read_only"
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "http://localhost:4318/v1/traces"
    logging:
      export:
        otlp:
          endpoint: "http://localhost:4318/v1/logs"
    resource-attributes:
      deployment.environment: "local"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

external:
  endpoint:
    user-api:
      domain: "localhost"
      port: "8080"
    product-api:
      domain: "localhost"
      port: "8081"