spring:
  application:
    name: "product-api"
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  web:
    resources:
      add-mappings: false
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
    remote:
      restart:
        enabled: false
  datasource:
    url: "${DATASOURCE_URL}"
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-init-sql: "SELECT 1"

server:
  shutdown: "graceful"
  compression:
    enabled: true

mybatis:
  mapper-locations: "classpath*:/jp/kukv/product_api/infrastructure/datasource/**/*.xml"
  type-handlers-package: "jp.kukv.product_api.infrastructure._configuration.mybatis.typehandler"
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: "${spring.application.name}"
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true
  otlp:
    tracing:
      endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces"
    metrics:
      endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics"
    logs:
      endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs"
otel:
  exporter:
    otlp:
      endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  resource:
    attributes:
      service.name: "${spring.application.name}"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  packages-to-scan: "jp.kukv.product_api.presentation.endpoint"
  paths-to-match: "/v1/**"
